---
title: Farisa
baseURL: https://vitoko.netlify.app/
languageCode: id
defaultContentLanguage: id
preserveTaxonomyNames: true
metaDataFormat: yaml
permalinks:
  authors: "/author/:slug/"
  tags: "/tag/:slug/"
  categories: "/category/:slug/"
  pages: "/:slug/"
  collections: "/collection/:slug/"
  color: "/:slug/"
  shop: "/:slug/"
  blog: "/:slug/"
outputs:
  home:
  - HTML
  page:
  - HTML
  section:
  - HTML
params:
  description: Temo toko online HUGO terbaik di Indonesia
  favicon: uploads/favicon.png
  is_statically: false
  author: Akhlis
  mainSection:
  - shop
taxonomies:
  tag: tags
  category: categories
  author: authors
  brand: brand
  collection: collections
  color: color
disableKinds:
- RSS
imaging:
  quality: 100
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
build:
  writeStats: true
menu:
  main:
  - identifier: fashion
    name: fashion
    url: fashion
    weight: 
    parent: ''
    params:
      class: ''
  - identifier: home
    name: Home
    url: "/"
    weight: 1
    params:
      class: ''
    parent: ''
  - identifier: hijacket
    name: Katalog Hijacket
    url: "/hijacket"
    weight: 2
    params:
      class: ''
    parent: ''
  - identifier: avia
    name: Hijacket Avia
    url: "/warna"
    parent: hijacket
    weight: 1
    params:
      class: ''
  - identifier: shop
    name: Shop
    url: "/shop"
    weight: 4
    params:
      class: ''
    parent: ''
  - identifier: alcavella
    name: Katalog Alcavella
    url: "/alcavella"
    weight: 3
    params:
      class: ''
    parent: ''
  - identifier: blog
    name: Blog
    url: "/blog"
    weight: 5
    params:
      class: ''
    parent: ''
