title: Vitoko
baseURL: /
LanguageCode: id
preserveTaxonomyNames: true
metaDataFormat: yaml
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  pages: '/:slug/'
  collections: '/collection/:slug/'
  color: '/:slug/'
  shop: '/:slug/'
outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
params:
  palette: pinkgrey
  colors:
    header_text: ''
  description: Jaket Muslimah Khusus Hijaber
  author: Akhlis
  contact:
    name: Anisa
    email: hijacket.cs@gmail.com
    whatsapp: '6285156514890'
    shop_name: Hijacket.net
  shipping:
    origin_city: '106'
    origin_province: order
    jne_oke: true
    jne_reg: true
    jne_yes: true
    pos_paket_kilat_khusus: true
    pos_express_next_day_barang: false
    tiki_eco: false
    tiki_reg: true
    tiki_ons: false
    jnt_ez: true
    wahana_normal: false
    sicepat_reg: true
    sicepat_best: true
    lion_regpack: false
    ninja_standard: false
  massUpdateStock: false
  dateFormat: 2 January 2006
  share_button: true
  social_share:
    facebook: true
    twitter: true
    whatsapp: true
    telegram: true
    mail: true
  post_author: true
  post_navigation: true
  mainSection:
    - shop
  header:
    type: header
    title: Starter
    logo: images/logo-hijacket.png
    has_nav: false
    sticky_nav: true
    has_navbar: true
    nav_links:
      - type: action
        template: action
        label: Features
        url: /features
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog
        style: link
      - type: action
        template: action
        label: Shop
        url: /shop
        style: link
      - type: action
        template: action
        label: Style Guide
        url: /style-guide
        style: link
      - type: action
        template: action
        label: About
        url: /about
        style: link
      - type: action
        template: action
        label: Contact Us
        url: /contact
        style: primary
    has_social: true
    social_links:
      - type: social
        template: social
        label: Facebook
        icon: facebook
        url: 'https://facebook.com/hijacket.net'
        style: link
        new_window: true
      - type: social
        template: social
        label: Twitter
        icon: twitter
        url: 'https://twitter.com/hijacket'
        style: link
        new_window: true
      - type: social
        template: social
        label: Instagram
        icon: instagram
        url: 'https://www.instagram.com/hijacket_net'
        style: link
        new_window: true
      - type: social
        template: social
        label: Telegram
        icon: telegram
        url: 'https://t.me/hijacket.net'
        style: link
        new_window: true
  sidebar:
    has_widget: true
    recent_num: 8
    sections:
      - type: widget_recent_post
      - type: widget_categories
      - type: widget_tags
  footer:
    type: footer
    has_widget: true
    sections:
      - type: widget_menu
        title: Informasi
        links:
          - label: Syarat dan Ketentuan
            url: /syarat-dan-ketentuan
          - label: Tentang Kami
            url: /tentang-kami
          - label: Kontak Kami
            url: /kontak-kami
          - label: FAQ
            url: /faq
      - type: widget_menu
        title: Bantuan
        links:
          - label: Cara Belanja
            url: /cara-order
          - label: Konfirmasi Pembayaran
            url: /konfirmasi-pembayaran
          - label: Panduan Ukuran
            url: /panduan-ukuran
          - label: Give Away
            url: /give-away
      - type: widget_contact
        title: Kontak Kami
        phone: 123456789
        whatsapp: 6285156514890
        email: hijacket.cs@gmail.com
        address: 'Jl. Mahmud No. 109 Rahayu, Margaasih, Kab. Bandung. 40218'
    has_social: true
    social_links:
      - label: Facebook
        icon: facebook
        url: 'https://facebook.com/hijacket.net'
        style: link
        new_window: true
      - label: Twitter
        icon: twitter
        url: 'https://twitter.com/hijacket'
        style: link
        new_window: true
      - label: Instagram
        icon: instagram
        url: 'https://www.instagram.com/hijacket_net'
        style: link
        new_window: true
      - label: Telegram
        icon: telegram
        url: 'https://t.me/hijacket.net'
        style: link
        new_window: true
    content: >-
      &copy; Copyright 2020 <a href="/">Hijacket.net </a>| Official Partner Of
      Hijacket Brand Indonesia.
taxonomies:
  tag: tags
  category: categories
  author: authors
  brand: brand
  collection: collections
  color: color
disableKinds:
  - RSS
imaging:
  quality: 90
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
build:
  writeStats: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
      params:
        has_submenu: false
    - identifier: hijacket
      name: Katalog Hijacket
      url: /hijacket
      weight: 2
      params:
        has_submenu: true
    - identifier: shop
      name: Micro Mask
      url: /micromask
      weight: 4
      params:
        has_submenu: false
    - identifier: alcavella
      name: Katalog Alcavella
      url: /alcavella
      weight: 3
      params:
        has_submenu: true
    - identifier: warna
      name: Koleksi Warna
      url: /warna
      weight: 5
      params:
        has_submenu: false
    - identifier: avia
      name: Hijacket Avia
      url: /warna
      parent: hijacket
      weight: 1
