---
title: Farisa
baseURL: https://vitoko.netlify.app/
languageCode: id
defaultContentLanguage: id
preserveTaxonomyNames: true
metaDataFormat: yaml
permalinks:
  authors: "/author/:slug/"
  tags: "/tag/:slug/"
  categories: "/category/:slug/"
  pages: "/:slug/"
  collections: "/collection/:slug/"
  color: "/:slug/"
  shop: "/:slug/"
  blog: "/:slug/"
outputs:
  home:
  - HTML
  page:
  - HTML
  section:
  - HTML
params:
  description: Temo toko online HUGO terbaik di Indonesia
  favicon: uploads/favicon.png
  is_statically: false
  author: Akhlis
  mainSection:
  - shop
taxonomies:
  tag: tags
  category: categories
  author: authors
  brand: brand
  collection: collections
  color: color
disableKinds:
- RSS
imaging:
  quality: 100
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
build:
  writeStats: true
