---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5fc960760b4f7d001d6d0d59/webhook/forestry
sections:
- type: heading
  label: Website
- type: document
  path: config.yaml
  label: Global Setting
- type: document
  path: data/theme.yaml
  label: Theme setting
- type: document
  path: data/header.yaml
  label: Header
- type: document
  path: data/sidebar.yaml
  label: Sidebar
- type: document
  path: data/footer.yaml
  label: Footer
- type: heading
  label: Pages
- type: directory
  path: content
  label: Page
  create: all
  match: "**/*"
  new_doc_ext: ".md"
upload_dir: uploads/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
